// characters.js
export const characters = [
    { char: "Dụ", img: "img/Du.webp" },
    { char: "Diệp", img: "img/Diep.webp" },
    { char: "Lam", img: "img/Lam.webp" },
    { char: "Duệ", img: "img/Due.webp" },
    { char: "Lư", img: "img/Lu.webp" },
    { char: "Chu", img: "img/Chu.webp" },
    { char: "Tranh", img: "img/Tranh.webp" },
    { char: "Cao", img: "img/Cao.webp" },
    { char: "Hàn", img: "img/Han.webp" },
    { char: "Lâu", img: "img/Lau.webp" },
    { char: "Hoàng", img: "img/Hoang.webp" },
    { char: "Kiều", img: "img/Kieu.webp" },
    { char: "Vương", img: "img/Vuong.webp" },
    { char: "Tống", img: "img/Tong.webp" },
    { char: "Tán", img: "img/Tan.webp" },
    { char: "Tiêu", img: "img/Tieu.webp" },
    { char: "Tôn", img: "img/Ton.webp" },
    { char: "Bao", img: "img/Bao.webp" },
    { char: "La", img: "img/La.webp" },
    { char: "An", img: "img/An.webp" },
    { char: "Ngụy", img: "img/Nguy.webp" },
    { char: "Phương", img: "img/Phuong.webp" },
    { char: "Nhu", img: "img/Nhu.webp" },
    { char: "Quả", img: "img/Qua.webp" },
    { char: "Mạc", img: "img/Mac.webp" },
    { char: "Quan", img: "img/Quan.webp" },
    { char: "Trịnh", img: "img/Trinh.webp" },
    { char: "Bình", img: "img/Binh.webp" }
];
