// characters.js
export const characters = [
    { char: "Dụ", img: "matching_game/images/Cá Dụ 1.webp" },
    { char: "Diệp", img: "matching_game/images/Cáo Diệp 1.webp" },
    { char: "Lam", img: "matching_game/images/Cáo tuyết Lam 1.webp" },
    { char: "Duệ", img: "matching_game/images/Chuột Duệ 1.webp" },
    { char: "Lư", img: "matching_game/images/Corgi Lư 1.webp" },
    { char: "Chu", img: "matching_game/images/Cụt Chu 1.webp" },
    { char: "Tranh", img: "matching_game/images/Hamster Tranh 1.webp" },
    { char: "Cao", img: "matching_game/images/Thỏ Cao 1.webp" },
    { char: "Hàn", img: "matching_game/images/Hổ Hàn 1.webp" },
    { char: "Lâu", img: "matching_game/images/Hổ trắng Lâu 1.webp" },
    { char: "Hoàng", img: "matching_game/images/Sư tử Hoàng 1.webp" },
    { char: "Kiều", img: "matching_game/images/Vịt vô tri Kiều 1.webp" },
    { char: "Vương", img: "matching_game/images/Mèo Vương 1.webp" },
    { char: "Tống", img: "matching_game/images/Hổ con Tống 1.webp" },
    { char: "Tán", img: "matching_game/images/Hồ ly Tán.webp" },
    { char: "Tiêu", img: "matching_game/images/Sóc chuột Tiêu.webp" },
    { char: "Tôn", img: "matching_game/images/Báo hoa Tôn.webp" },
    { char: "Bao", img: "matching_game/images/Cún bự Bao 1.webp" },
    { char: "La", img: "matching_game/images/Cún La 1.webp" },
    { char: "An", img: "matching_game/images/Cú An 1.webp" },
    { char: "Ngụy", img: "matching_game/images/Lão cẩu Ngụy 1.webp" },
    { char: "Phương", img: "matching_game/images/Linh miêu bự Phương 1.webp" },
    { char: "Nhu", img: "matching_game/images/Mèo Nhu 1.webp" },
    { char: "Quả", img: "matching_game/images/Mèo Quả 1.webp" },
    { char: "Mạc", img: "matching_game/images/Quạ Mạc 1.webp" },
    { char: "Quan", img: "matching_game/images/Hải ly Quan 1.webp" },
    { char: "Trịnh", img: "matching_game/images/Cá Trịnh 1.webp" },
    { char: "Bình", img: "matching_game/images/Tanuki Bình.webp" }
];
